spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://payment1.crqwaqysc1zd.ap-southeast-2.rds.amazonaws.com:3306/payment?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rr8602
    password: wjdqudwls1!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # show_sql: true
        format_sql: true
        use_sql_comments: true # JPQL? ?? ?? ?? ?
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

management:
  endpoint:
    health:
      show-details: always

external:
  api:
    url: https://development.codef.io/v1/kr/card/p/account/approval-list
